--select * from [dbo].[AdminAssistant]

--select * from [dbo].[Project]
--select * from [dbo].[SubProject]
--select * from [dbo].[SubProjectBudget]
--select * from [dbo].[SubProjectCoInvestigator]
--select * from [dbo].[ProjectLeader]
--select * from [dbo].[ProjectManager]
--select * from [dbo].[ProjectMentor]
--select * from [dbo].[SubProjectCoInvestigator]
--select * from [dbo].[SubProjectCollaborator]
--select * from [dbo].[SubProjectFinOfficer]
--select * from [dbo].[SubProjectFinRep]
--select * from [dbo].[SubProjectPI]

TRUNCATE TABLE [AdminAssistant]
TRUNCATE TABLE [Contact]
TRUNCATE TABLE [ContactAdminFor]
TRUNCATE TABLE [ContactAssistantFor]
TRUNCATE TABLE [ContactEmail]
TRUNCATE TABLE [ContactInstitution]
TRUNCATE TABLE [ContactPhone]
TRUNCATE TABLE [Institution]
TRUNCATE TABLE [InstitutionCommRep]
TRUNCATE TABLE [PeopleGroupContact]
TRUNCATE TABLE [PeopleGroupProject]
TRUNCATE TABLE [ProjectCoFunder]
TRUNCATE TABLE [Project]
TRUNCATE TABLE [SubProject]
TRUNCATE TABLE [SubProjectBudget]
TRUNCATE TABLE [SubProjectCoInvestigator]
TRUNCATE TABLE [ProjectLeader]
TRUNCATE TABLE [ProjectManager]
TRUNCATE TABLE [ProjectMentor]
TRUNCATE TABLE [SubProjectCoInvestigator]
TRUNCATE TABLE [SubProjectCollaborator]
TRUNCATE TABLE [SubProjectFinOfficer]
TRUNCATE TABLE [SubProjectFinRep]
TRUNCATE TABLE [SubProjectPI]
TRUNCATE TABLE [SubProjectManager]
